version: '3.8'

services:
  traefik:
    image: docker.io/library/traefik:v3.5.3
    container_name: traefik
    restart: unless-stopped
    command:
      # Use file provider instead of Docker provider
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-letsencrypt:/letsencrypt:z
      - ./traefik.yml:/etc/traefik/traefik.yml:z
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:z
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - proxy

  contacts-calendar-downloader:
    build: .
    container_name: contacts-calendar-downloader
    restart: unless-stopped
    environment:
      # Core Configuration
      - DATABASE=${DATABASE:-/app/data/credentials.db}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS:-/app/credentials/google.json}
      - MICROSOFT_CREDENTIALS=${MICROSOFT_CREDENTIALS:-/app/credentials/microsoft.json}
      
      # Server Configuration
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-5000}
      - PROTOCOL=${PROTOCOL:-https}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      
      # OAuth Configuration
      - GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI:-${PROTOCOL}://${HOST}:${PORT}/google/oauth2callback}
      - MICROSOFT_OAUTH_REDIRECT_URI=${MICROSOFT_OAUTH_REDIRECT_URI:-${PROTOCOL}://${HOST}:${PORT}/microsoft/oauth2callback}

      # API Configuration
      - PERSON_FIELDS=${PERSON_FIELDS:-names,emailAddresses,phoneNumbers,addresses,organizations,birthdays}
      - PAGE_SIZE=${PAGE_SIZE:-1000}
      
      # Flask Configuration (compatibility)
      - FLASK_ENV=${FLASK_ENV:-production}
    ports:
      - "8000:8000"
    volumes:
      # Persist database and credentials
      - app-data:/app/data:z
      # Credentials for Google API (mount your credentials.json here)
      - ./credentials/:/app/credentials/:z
    networks:
      - proxy
    depends_on:
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  proxy:
    driver: bridge

volumes:
  traefik-letsencrypt:
    driver: local
  app-data:
    driver: local
