version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:17.6-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-downloader}
      - POSTGRES_USER=${POSTGRES_USER:-downloader}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - proxy
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-downloader}"]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: docker.io/library/traefik:v3.5.3
    container_name: traefik
    restart: unless-stopped
    command:
      # Use file provider instead of Docker provider
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-letsencrypt:/letsencrypt:z
      - ./traefik.yml:/etc/traefik/traefik.yml:z
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:z
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - proxy

  contacts-calendar-downloader:
    build: .
    container_name: contacts-calendar-downloader
    restart: unless-stopped
    environment:
      # PostgreSQL Configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-downloader}
      - POSTGRES_USER=${POSTGRES_USER:-downloader}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      
      # Core Configuration
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS:-/app/credentials/google.json}
      - MICROSOFT_CREDENTIALS=${MICROSOFT_CREDENTIALS:-/app/credentials/microsoft.json}
      
      # Server Configuration
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-5000}
      - PROTOCOL=${PROTOCOL:-https}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      
      # OAuth Configuration
      - GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI}
      - MICROSOFT_OAUTH_REDIRECT_URI=${MICROSOFT_OAUTH_REDIRECT_URI}

      # API Configuration
      - PERSON_FIELDS=${PERSON_FIELDS:-names,emailAddresses,phoneNumbers,addresses,organizations,birthdays}
      - PAGE_SIZE=${PAGE_SIZE:-1000}
      
      # Flask Configuration (compatibility)
      - FLASK_ENV=${FLASK_ENV:-production}
    ports:
      - "8000:8000"
    volumes:
      # Credentials for Google API (mount your credentials.json here)
      - ./credentials/:/app/credentials/:z
    networks:
      - proxy
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  proxy:
    driver: bridge

volumes:
  traefik-letsencrypt:
    driver: local
  postgres-data:
    driver: local
  app-data:
    driver: local
